image:
  repository: registry.cube.local:5000/cnpj-batch
  tag: v0.9
database:
  host: 192.168.1.250
  port: 5432
  name: mux
  properties: currentSchema=cnpj&sslmode=require&search_path=cnpj&currentSchema=cnpj
schedule: "0 2 * * *"
suspend: "false"