image:
  repository: registry.cube.local:5000/cnpj-batch
  tag: v1.0
database:
  host: 192.168.1.250
  port: 5432
  name: mux
  properties: currentSchema=cnpj&sslmode=require&search_path=cnpj
schedule: "0 0 * * *"